# Generated by Django 2.0.5 on 2018-05-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0002_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
